credentials:
  usernames:
    smart_admin:
      email: smart@admin.com
      name: S.M.A.R.T. Admin
      password: 'PASTE_YOUR_HASH_HERE'
cookie:
  expiry_days: 30
  key: smart_ai_key
  name: smart_ai_cookie
preauthorized:
  emails:
  - smart@admin.com